version: '3.2'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      net:
        aliases:
          - redis

  hello-world:
    image: hello-world:0.0.1-SNAPSHOT
    container_name: hello-world
    environment:
      - SPRING_PROFILES_ACTIVE=redis
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - 8080:8080
    networks:
      net:
        aliases:
          - hello-world

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      - EUREKA_SERVER=service-discovery
      - EUREKA_PORT=8761
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - service-discovery
    links:
      - service-discovery
    networks:
      net:
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_HTTP_PORT=3000
    networks:
      net:
        aliases:
          - grafana

  setup_grafana_datasource:
    image: appropriate/curl
    container_name: setup_grafana_datasource
    depends_on:
      - grafana
    volumes:
      - ./create-datasource-and-dashboard.sh:/create.sh:ro
    command: /create.sh
    networks:
      net:
        aliases:
          - setup_grafana_datasource

networks:
  net: