# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
      #      metrics_path: '/actuator/prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['0.0.0.0:9090']

#  - job_name: 'hello-world'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 15s
#    static_configs:
#      - targets: ['hello-world:8081', 'hello-world2:8082', 'hello-world3:8083']

  - job_name: node-exporter
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    honor_labels: true
    consul_sd_configs:
      - server: consul:8500
        services: [node-exporter]
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: ^.*,_team=storefront,.*$
        action: keep
      - source_labels: [__meta_consul_tags]
        regex: .*,_app=([^,]+),.*
        replacement: ${1}
        target_label: _app
      - source_labels: [__meta_consul_tags]
        regex: .*,_service=([^,]+),.*
        replacement: ${1}
        target_label: _service
      - source_labels: [__meta_consul_tags]
        regex: .*,_hostname=([^,]+),.*
        replacement: ${1}
        target_label: _hostname
      - source_labels: [__meta_consul_tags]
        regex: .*,_environment=([^,]+),.*
        replacement: ${1}
        target_label: _environment
      - source_labels: [__meta_consul_tags]
        regex: .*,_cluster=([^,]+),.*
        replacement: ${1}
        target_label: _cluster
      - source_labels: [__meta_consul_tags]
        regex: .*,_es_role=([^,]+),.*
        replacement: ${1}
        target_label: _es_role
      - source_labels: [__meta_consul_tags]
        regex: .*,_team=([^,]+),.*
        replacement: ${1}
        target_label: _team